# Generated by Django 4.2.3 on 2023-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=100)),
                ("l_name", models.EmailField(max_length=100)),
                ("email", models.CharField(max_length=15)),
            ],
        ),
    ]
